=== dgutper960/DavidGutierrez_UD4_LMSGI/Editorial/Editorial_dtd.dtd
<!ELEMENT Informe (Cabecera,Tabla)>
<!ELEMENT Cabecera (Titulo,Contenido,Descripcion,Fecha)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Contenido (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Tabla (Region+,Trimestre,Libros_vendidos)>
<!ELEMENT Region (Norte?,Centro?,Sur?)>
<!ELEMENT Norte (#PCDATA|TrimestreTabla|Libros_vendidos|Trimestre_Tabla|libros_vendidos)*>
<!ELEMENT TrimestreTabla (#PCDATA)>
<!ELEMENT Libros_vendidos (#PCDATA)>
<!ELEMENT Trimestre_Tabla (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>
<!ELEMENT Centro (#PCDATA|Trimestre_Tabla|Libros_vendidos)*>
<!ELEMENT Sur (#PCDATA|Trimestre_Tabla|Libros_vendidos)*>
<!ELEMENT Trimestre (#PCDATA)>

=== dgutper960/DavidGutierrez_UD4_LMSGI/Editorial/Editorial_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Cabecera SYSTEM "Editorial_dtd.dtd">
<Cabecera
  <Empresa>Ediciones Aranda</Empresa>
  <Titulo>Informe regional del ventas</Titulo>
  <Descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</Descripcion>
  <Fecha>Fecha: 30/12/2009</Fecha>
</Cabecera>
<Informe>
  <Tabla>
    <Region>Norte
      <Trimestre>1</Trimestre>
      <Libros_vendidos>24000</Libros_vendidos>
      <Trimestre>2</Trimestre>
      <Libros_vendidos>38600</Libros_vendidos>
      <Trimestre>3</Trimestre>
      <Libros_vendidos>NO_INFO</Libros_vendidos>
      <Trimestre>4</Trimestre>
      <Libros_vendidos>NO_INFO</Libros_vendidos>
    </Region>
    <Region>Centro
      <Trimestre>1</Trimestre>
      <Libros_vendidos>NO_INFO</Libros_vendidos>
      <Trimestre>2</Trimestre>
      <Libros_vendidos>1608</Libros_vendidos>
      <Trimestre>3</Trimestre>
      <Libros_vendidos>25000</Libros_vendidos>
      <Trimestre>4</Trimestre>
      <Libros_vendidos>29000</Libros_vendidos>
    </Region>
    <Region>Sur
      <Trimestre>1</Trimestre>
      <Libros_vendidos>27000</Libros_vendidos>
      <Trimestre>2</Trimestre>
      <Libros_vendidos>31400</Libros_vendidos>
      <Trimestre>3</Trimestre>
      <Libros_vendidos>40100</Libros_vendidos>
      <Trimestre>4</Trimestre>
      <Libros_vendidos>30000</Libros_vendidos>
    </Region>
  </Tabla>
</Informe>
