=== dgutper960/DavidGutierrez_UD4_LMSGI/Clientes/Clientes_dtd.dtd
<!ELEMENT Clientes (Sede)>
<!ELEMENT Sede (Direcci贸n,Empleado,Fecha_alta,Descripci贸n,Cliente)>
<!ATTLIST Sede codigo NMTOKEN #REQUIRED>
<!ELEMENT Direcci 贸n (#PCDATA)>
<!ELEMENT Empleado (#PCDATA)>
<!ELEMENT Fecha_alta (#PCDATA)>
<!ELEMENT Descripci 贸n (#PCDATA)>
<!ELEMENT Cliente (Num_viviendas,Coste,Resumen,Plazo_alta)>
<!ATTLIST Cliente codigo NMTOKEN #REQUIRED>
<!ELEMENT Num_viviendas (#PCDATA)>
<!ELEMENT Coste (#PCDATA)>
<!ELEMENT Resumen (#PCDATA)>
<!ELEMENT Plazo_alta (#PCDATA)>

=== dgutper960/DavidGutierrez_UD4_LMSGI/Clientes/Clientes_dtd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Clientes SYSTEM "Clientes_dtd.dtd">
<Clientes
    <Sede codigo="A4569632">
		<Dirección>Calle Atapuerca, 5, Planta Baja</Dirección>
		<Empleado>Rodrigo Diaz de Vivar</Empleado>
		<Fecha_alta>22/04/1997</Fecha_alta>
		<Descripción>Lo que quiera que sea será</Descripción>
		<Cliente codigo="BGO-111">
	  		<Num_viviendas>4</Num_viviendas>
	  		<Coste>900</Coste>
	  		<Resumen>Las Casas Bonitas</Resumen>
	  		<Plazo_alta>23/01/23</Plazo_alta>
		</Cliente>
    </Sede>
</Clientes>
